### PR TITLE
Mismatch json2csv fields&filedNames. #1

### PR DESCRIPTION
**Pull request by drfaustusfade**
Mismatch json2csv fields&filedNames. #1

### CODE REVIEW

**Comment by drfaustusfade** [comment]
local.js had trailing carriage return in the name, that caused issues while cloning repository.

**Comment by drfaustusfade** [comment]
Auto whitespace removal present for other lines.

**Comment by pfitzpaddy** [comment]
local.js is now in .gitignore but somehow it is now included in the repo. Can you take a look at this and re-submit the pull request without the local.js. Not sure how i even managed to do that, perhaps a commit from the virtual machine. Luckily its not the correct configuration!

**Comment by pfitzpaddy** [comment]
I didnt get to merge this, can you reopen or is there some reason its closed. Thanks

**Comment by drfaustusfade** [comment]
It did close automatically on repo reset. I will reopen new after resolving local.js file name issue #4

**Comment by pfitzpaddy** [comment]
ok cheers

**Pull request closed without merging**
