### PR TITLE
Feature cp prev report

### PR DESCRIPTION
**Pull request by drfaustusfade**
branch of https://github.com/pfitzpaddy/ngm-reportEngine/pull/15

1. get stock report previous report api

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Merged on DEV and PROD

**Comment by pfitzpaddy** [comment]
One question on this. Does it clear the $id from the copied record? And where does it update the report month?

**Comment by drfaustusfade** [comment]
it copies next fields
                  cluster_id: s.cluster_id, 
                  stock_item_type: s.stock_item_type, 
                  stock_item_name: s.stock_item_name, 
                  stock_item_purpose_id: s.stock_item_name, 
                  stock_item_purpose_name: s.stock_item_purpose_name, 
                  stock_status_id: s.stock_status_id, 
                  stock_status_name: s.stock_status_name, 
                  unit_type_id: s.unit_type_id, 
                  unit_type_name: s.unit_type_name, 
                  number_in_stock: s.number_in_stock, 
                  number_in_pipeline: s.number_in_pipeline, 
                  beneficiaries_covered: s.beneficiaries_covered 
and loops via existing getCleanStocks

**Comment by pfitzpaddy** [comment]
Ah so in fact, the $id (non-existant) and months are the same as if it was added as a new record. Brilliant.

**Comment by pfitzpaddy** [comment]
Merged on DEV and PROD

**Pull request merged**
